name: Semantic Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Copy .releaserc
        run: cp .github/.releaserc .

      # - name: Install Dependencies
      #   run: npm ci

      - name: Release
        run: npx semantic-release@21.0.7 @semantic-release/changelog @semantic-release/git
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
